language: php

php:
    - 7.2
    
services:
    - docker
    - mysql
before_install:
    - composer update
    - mysql -u root --password="" < DB.sql
    
jobs:
    include:
        - stage: "Building docker image"
          script: 
          - docker pull php
          - docker build -t recrutement .
          - docker run -it -p 8080:80 recrutement
          - docker ps -a
          - echo "Running job 1.1"
        - stage: "Executing security tests"
          script: echo "Running security test"