language: php

php:
    - 7.2
    
services:
    - docker
    - mysql
before_install:
    - composer update
    - mysql -u root -e "CREATE DATABASE IF NOT EXISTS recrutementTest;USE recrutementTest;CREATE TABLE IF NOT EXISTS admin(ID INT primary key AUTO_INCREMENT,NOM VARCHAR(50) NOT NULL ,PRENOMS VARCHAR(150) NOT NULL ,USERNAME VARCHAR(100) NOT NULL ,PASSWORD TEXT NOT NULL);CREATE TABLE IF NOT EXISTS gestionnaire(ID INT primary key AUTO_INCREMENT,NOM VARCHAR(50) NOT NULL ,PRENOMS VARCHAR(150) NOT NULL ,USERNAME VARCHAR(100) NOT NULL ,PASSWORD TEXT NOT NULL,ADMIN_ID INT);CREATE TABLE IF NOT EXISTS technicien(ID INT primary key AUTO_INCREMENT,NOM VARCHAR(50) NOT NULL ,PRENOMS VARCHAR(150) NOT NULL ,USERNAME VARCHAR(100) NOT NULL ,PASSWORD TEXT NOT NULL,ADMIN_ID INT);CREATE TABLE IF NOT EXISTS type_vehicule(ID INT PRIMARY KEY AUTO_INCREMENT,TYPE VARCHAR(50) NOT NULL);CREATE TABLE IF NOT EXISTS vehicule(ID INT PRIMARY KEY AUTO_INCREMENT,TYPE_VEHICULE_ID INT,DATE_ACHAT DATE,GESTIONNAIRE_ID INT);CREATE TABLE IF NOT EXISTS probleme(ID INT PRIMARY KEY AUTO_INCREMENT,TECHNICIEN_ID INT,VEHICULE_ID INT,DETAIL TEXT);CREATE TABLE IF NOT EXISTS maintenance(ID INT PRIMARY KEY AUTO_INCREMENT,DATE_DEBUT DATE,DATE_FIN DATE,SUJET TEXT,DESCRIPTION TEXT,PROBLEME_ID INT);CREATE TABLE IF NOT EXISTS intervenir(ID INT PRIMARY KEY AUTO_INCREMENT,TECHNICIEN_ID INT,MAINTENANCE_ID INT);CREATE TABLE IF NOT EXISTS piece(ID INT PRIMARY KEY AUTO_INCREMENT,PIECE TEXT NOT NULL ,MAINTENANCE_ID INT);INSERT INTO admin values (NULL, 'ADMIN', 'ADMIN', 'admin', 'f7c3bc1d808e04732adf679965ccc34ca7ae3441');"
    
jobs:
    include:
        - stage: "Building docker image"
          script: 
          - docker pull php
          - docker build -t recrutement .
          - docker run -it -p 8080:80 recrutement
          - docker ps -a
          - echo "Running job 1.1"
        - stage: "Executing security tests"
          script: echo "Running security test"