language: php

php:
    - 7.2
    
services:
    - docker
    
before_install:
    - composer install
    
jobs:
    include:
        - stage: "Building docker image"
          script: "Running job 1"
        - stage: "Executing security tests"
          script: "Running security test"