language: php

php:
    - 7.2
    
services:
    - docker
    
before_install:
    - composer update
    
jobs:
    include:
        - stage: "Building docker image"
          script: 
          - docker pull php
          - docker build -t recrutement
          - docker run -it --rm --name my-running-app my-php-app
          - docker ps -a
          - echo "Running job 1.1"
        - stage: "Executing security tests"
          script: echo "Running security test"