CREATE DATABASE recrutementTest;

USE recrutementTest;



CREATE TABLE ADMIN (
  ID INT primary key,
  NOM VARCHAR(50) NOT NULL ,
  PRENOMS VARCHAR(150) NOT NULL ,
  USERNAME VARCHAR(100) NOT NULL ,
  PASSWORD TEXT NOT NULL
);

CREATE TABLE GESTIONNAIRE(
 ID INT primary key,
 NOM VARCHAR(50) NOT NULL ,
 PRENOMS VARCHAR(150) NOT NULL ,
 USERNAME VARCHAR(100) NOT NULL ,
 PASSWORD TEXT NOT NULL,
 ADMIN_ID INT FOREIGN KEY REFERENCES ADMIN(ID)
);

CREATE TABLE TECHNICIEN (
  ID INT primary key,
  NOM VARCHAR(50) NOT NULL ,
  PRENOMS VARCHAR(150) NOT NULL ,
  USERNAME VARCHAR(100) NOT NULL ,
  PASSWORD TEXT NOT NULL,
  ADMIN_ID INT FOREIGN KEY REFERENCES ADMIN(ID)
);

CREATE TABLE TYPE_VEHICULE (
  ID INT PRIMARY KEY,
  TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE VEHICULE (
  ID INT PRIMARY KEY ,
  TYPE_VEHICULE_ID INT FOREIGN KEY REFERENCES TYPE_VEHICULE(ID),
  DATE_ACHAT DATE,
  GESTIONNAIRE_ID INT FOREIGN KEY REFERENCES GESTIONNNAIRE(ID)
);

CREATE TABLE PROBLEME (
  TECHNICIEN_ID INT FOREIGN KEY REFERENCES TECHNICIEN(ID),
  VEHICULE_ID INT FOREIGN KEY REFERENCES VEHICULE(ID),
  DETAIL TEXT,
  PRIMARY KEY (TECHNICIEN_ID, VEHICULE_ID)
);

CREATE TABLE MAINTENANCE (
  DATE_DEBUT DATE,
  DATE_FIN DATE,
  SUJET TEXT,
  DESCRIPTION TEXT,
  PROBLEME_ID INT FOREIGN KEY REFERENCES PROBLEME(ID)
);

CREATE TABLE INTERVENIR (
  TECHNICIEN_ID INT FOREIGN KEY REFERENCES TECHNICIEN(ID),
  MAINTENANCE_ID INT FOREIGN KEY REFERENCES MAINTENANCE(ID),
  PRIMARY KEY (TECHNICIEN_ID, MAINTENANCE_ID)
);

CREATE TABLE PIECE(
  ID INT PRIMARY KEY ,
  PIECE TEXT NOT NULL ,
  MAINTENANCE_ID INT FOREIGN KEY REFERENCES MAINTENANCE(ID)
)