CREATE DATABASE recrutementTest;

USE recrutementTest;

CREATE TABLE ADMIN (
  ID INT primary key AUTO_INCREMENT,
  NOM VARCHAR(50) NOT NULL ,
  PRENOMS VARCHAR(150) NOT NULL ,
  USERNAME VARCHAR(100) NOT NULL ,
  PASSWORD TEXT NOT NULL
);

CREATE TABLE GESTIONNAIRE(
  ID INT primary key AUTO_INCREMENT,
 NOM VARCHAR(50) NOT NULL ,
 PRENOMS VARCHAR(150) NOT NULL ,
 USERNAME VARCHAR(100) NOT NULL ,
 PASSWORD TEXT NOT NULL,
 ADMIN_ID INT ,
 FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ID)
);

CREATE TABLE TECHNICIEN (
   ID INT primary key AUTO_INCREMENT,
  NOM VARCHAR(50) NOT NULL ,
  PRENOMS VARCHAR(150) NOT NULL ,
  USERNAME VARCHAR(100) NOT NULL ,
  PASSWORD TEXT NOT NULL,
  ADMIN_ID INT ,
  FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ID)
);

CREATE TABLE TYPE_VEHICULE (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE VEHICULE (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  TYPE_VEHICULE_ID INT,
  DATE_ACHAT DATE,
  GESTIONNAIRE_ID INT,
  FOREIGN KEY (GESTIONNAIRE_ID) REFERENCES GESTIONNAIRE(ID),
  FOREIGN KEY (TYPE_VEHICULE_ID) REFERENCES TYPE_VEHICULE(ID)
);

CREATE TABLE PROBLEME (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  TECHNICIEN_ID INT,
  VEHICULE_ID INT,
  DETAIL TEXT,
  FOREIGN KEY (TECHNICIEN_ID) REFERENCES TECHNICIEN(ID),
  FOREIGN KEY (VEHICULE_ID) REFERENCES VEHICULE(ID)
);

CREATE TABLE MAINTENANCE (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  DATE_DEBUT DATE,
  DATE_FIN DATE,
  SUJET TEXT,
  DESCRIPTION TEXT,
  PROBLEME_ID INT,
  FOREIGN KEY(PROBLEME_ID) REFERENCES PROBLEME(ID)
);

CREATE TABLE INTERVENIR (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  TECHNICIEN_ID INT,
  MAINTENANCE_ID INT,
  FOREIGN KEY (TECHNICIEN_ID) REFERENCES TECHNICIEN(ID),
  FOREIGN KEY (MAINTENANCE_ID) REFERENCES MAINTENANCE(ID)
);

CREATE TABLE PIECE(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  PIECE TEXT NOT NULL ,
  MAINTENANCE_ID INT,
  FOREIGN KEY (MAINTENANCE_ID) REFERENCES MAINTENANCE(ID)
);